import { Inter } from "next/font/google";
import "@/css/globals.css";
import Navbar from "@/components/Navbar";
import {Toaster} from "react-hot-toast"
import Sidebar from "@/components/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Welcome to MyStudyMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        <Navbar/>
        {/* <Sidebar/> */}
        {children}
      </body>
    </html>
  );
}
