import { Inter } from "next/font/google";

import Navbar from "../components/Navbar";
import {Toaster} from "react-hot-toast"
import "../css/globals.css"
const inter = Inter({ subsets: ["latin"] });




export const metadata = {
  title: "Welcome to MyStudyMate",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en" data-theme="colorblind">
      <body className={inter.className}>
        <Toaster/>
        <Navbar/>
        {/* <NotificationHandler/> */}
        {/* <Sidebar/> */}
     
          {children}
    
      </body>
    </html>
  );
}
