
export const metadata = {
  title: "Create new plan - MyStudyMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {children}
    </>
  );
}
