
export const metadata = {
  title: "Calendar - MyStudyMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
 
        {children}
      
    </>
  );
}
